name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Start Android Emulator
      run: |
        echo "no" | sdkmanager --install "system-images;android-29;google_apis;x86"
        emulator -avd test -no-snapshot-load -no-accel &
        android-wait-for-emulator
    - name: Run Unit Tests
      run: ./gradlew test
    - name: Run Android Instrumented Tests
      run: ./gradlew connectedAndroidTest
